export const actionTypes = {
  // Genre
  SET_SELECTED_GENRE: "SET_SELECTED_GENRE",
  SET_GENRES_LIST: "SET_GENRES_LIST",
  // Brand
  SET_SELECTED_BRAND: "SET_SELECTED_BRAND",
  SET_BRANDS_LIST: "SET_BRANDS_LIST",
  // Console
  SET_SELECTED_CONSOLE: "SET_SELECTED_CONSOLE",
  SET_CONSOLES_LIST: "SET_CONSOLES_LIST",
  // Game
  SET_SELECTED_GAME: "SET_SELECTED_GAME",
  SET_GAMES_LIST: "SET_GAMES_LIST",
  // Snackbar
  OPEN_SNACKBAR: "OPEN_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
};