export const actionTypes = {
  SET_SELECTED_GENRE: "SET_SELECTED_GENRE",
  SET_GENRES_LIST: "SET_GENRES_LIST",
  SET_SELECTED_BRAND: "SET_SELECTED_BRAND",
  SET_BRANDS_LIST: "SET_BRANDS_LIST",
  OPEN_SNACKBAR: "OPEN_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
};