export const actionTypes = {
  // Genre
  SET_SELECTED_GENRE: "SET_SELECTED_GENRE",
  SET_GENRES_LIST: "SET_GENRES_LIST",
  // Brand
  SET_SELECTED_BRAND: "SET_SELECTED_BRAND",
  SET_BRANDS_LIST: "SET_BRANDS_LIST",
  SET_BRANDS_LIST_MISC: "SET_BRANDS_LIST_MISC",
  // Console
  SET_SELECTED_CONSOLE: "SET_SELECTED_CONSOLE",
  SET_CONSOLES_LIST: "SET_CONSOLES_LIST",
  SET_CONSOLES_LIST_MISC: "SET_CONSOLES_LIST_MISC",
  // Game
  SET_SELECTED_GAME: "SET_SELECTED_GAME",
  SET_GAMES_LIST: "SET_GAMES_LIST",
  // Snackbar
  OPEN_SNACKBAR: "OPEN_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
  // GAMES LIST OPTIONS
  SET_GAMES_LIST_OPTION: "SET_GAMES_LIST_OPTION",
  SET_INITIAL_LETTER: "SET_INITIAL_LETTER",
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  SET_SORTING_KEY: "SET_SORTING_KEY",
  SET_SORTING_DIRECTION: "SET_SORTING_DIRECTION",
  // LOADING STATE
  SET_IS_LOADING: "SET_IS_LOADING",
  // USER AUTHENTICATION
  SET_AUTH_USER: "SET_AUTH_USER",
  // INFO TOTALS
  SET_INFO_TOTALS: "SET_INFO_TOTALS",

};